imports:
    - { resource: config_dev.yml }

framework:
    profiler:
        enabled: false

#web_profiler:
#    toolbar: false
#    intercept_redirects: false

swiftmailer:
    disable_delivery: true
