imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

ekino_new_relic:
    application_name: Lighthouse API tests

doctrine_mongodb:
    default_database: "%database_name%_%kernel.environment%_%karzer.thread%"

lighthouse_core:
    job:
        tube_prefix: "%database_name%_%kernel.environment%_%karzer.thread%"
