imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: %database_name%_%kernel.environment%
    document_managers:
        default:
            auto_mapping: true

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [LighthouseCoreBundle]
        directories: ["%kernel.root_dir%/../src"]

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        default_priorities:
            - json
            - "*/*"
    routing_loader:
        default_format: json
    view:
        view_response_listener: force
        formats:
          html: false
          xml: true
          json: true
        templating_formats:
            html: false
    exception:
        codes:
            'Lighthouse\CoreBundle\Exception\NotEmptyException': 409
        messages:
            'Lighthouse\CoreBundle\Exception\NotEmptyException': true

nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization', 'Link']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'LINK', 'UNLINK']
            max_age: 3600
        '^/oauth/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'LINK', 'UNLINK']
            max_age: 3600

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

fos_oauth_server:
    db_driver: mongodb
    client_class:        Lighthouse\CoreBundle\Document\Auth\Client
    access_token_class:  Lighthouse\CoreBundle\Document\Auth\AccessToken
    refresh_token_class: Lighthouse\CoreBundle\Document\Auth\RefreshToken
    auth_code_class:     Lighthouse\CoreBundle\Document\Auth\AuthCode
    service:
        user_provider: lighthouse.core.user.provider
        options:
            access_token_lifetime: 86400

nelmio_api_doc:
    name: Lighthouse API

ekino_new_relic:
    application_name: Lighthouse API
    api_key: 8e0222b451067be5425cf910998d1cc80412e63275b69d1
