#lighthouse.core:
#    resource: "@LighthouseCoreBundle/Controller"
#    type:     annotation
#    prefix:   /ap1/%lighthouse.core.api.version%/

lighthouse.core.article:
    resource: "@LighthouseCoreBundle/Controller/ProductController.php"
    type:     rest
    prefix: /api/1