services:
    jms_serializer.serialized_name_annotation_strategy:
        class: %jms_serializer.serialized_name_annotation_strategy.class%
        public: false
        arguments: ["@lighthouse.core.naming.as_is"]

    jms_serializer.metadata_driver:
        alias: lighthouse.core.serializer.metadata.driver.document

    doctrine_mongodb.odm.repository:
        class: Doctrine\ODM\MongoDB\DocumentRepository
        factory_service: doctrine_mongodb.odm.document_manager
        factory_method: getRepository

    lighthouse.core.document.repository.shop_product:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\ShopProductRepository
        arguments:
            - LighthouseCoreBundle:ShopProduct

    lighthouse.core.document.repository.invoice_product:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\InvoiceProductRepository
        arguments:
            - LighthouseCoreBundle:InvoiceProduct
