parameters:
    money.digits: 2

services:
    jms_serializer.serialized_name_annotation_strategy:
        class: %jms_serializer.serialized_name_annotation_strategy.class%
        public: false
        arguments: ["@lighthouse.core.naming.as_is"]

    jms_serializer.metadata_driver:
        alias: lighthouse.core.serializer.metadata.driver.document

    sensio_framework_extra.converter.doctrine.orm:
        class: %sensio_framework_extra.converter.doctrine.class%
        arguments: ["@doctrine_mongodb"]
        tags:
            - { name: request.param_converter, converter: doctrine.orm }

    doctrine:
        alias: doctrine_mongodb

    doctrine_mongodb.odm.repository:
        abstract: true
        class: Doctrine\ODM\MongoDB\DocumentRepository
        factory_service: doctrine_mongodb.odm.document_manager
        factory_method: getRepository

    #test.client:
    #    class: Lighthouse\CoreBundle\Test\Client\Client
    #    scope: prototype
    #    arguments:
    #        - @kernel
    #        - %test.client.parameters%
    #        - @test.client.history
    #        - @test.client.cookiejar


    lighthouse.core.document.repository.product:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\Product\ProductRepository
        arguments:
            - LighthouseCoreBundle:Product\Product

    lighthouse.core.document.repository.invoice:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\Invoice\InvoiceRepository
        arguments:
            - LighthouseCoreBundle:Invoice\Invoice

    lighthouse.core.document.repository.invoice_product:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\Invoice\Product\InvoiceProductRepository
        arguments:
            - LighthouseCoreBundle:Invoice\Product\InvoiceProduct

    lighthouse.core.document.repository.trial_balance:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\TrialBalance\TrialBalanceRepository
        arguments:
            - LighthouseCoreBundle:TrialBalance\TrialBalance

    lighthouse.core.document.repository.purchase:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\Purchase\PurchaseRepository
        arguments:
            - LighthouseCoreBundle:Purchase\Purchase

    lighthouse.core.document.repository.writeoff:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\WriteOff\WriteOffRepository
        arguments:
            - LighthouseCoreBundle:WriteOff\WriteOff

    lighthouse.core.document.repository.writeoff.product:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\WriteOff\Product\WriteOffProductRepository
        arguments:
            - LighthouseCoreBundle:WriteOff\Product\WriteOffProduct

    lighthouse.core.document.repository.classifier.group:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\Classifier\Group\Group
        arguments:
            - LighthouseCoreBundle:Classifier\Group\Group

    lighthouse.core.document.repository.classifier.category:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\Classifier\Category\Category
        arguments:
            - LighthouseCoreBundle:Classifier\Category\Category

    lighthouse.core.document.repository.classifier.subcategory:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\Classifier\SubCategory\SubCategory
        arguments:
            - LighthouseCoreBundle:Classifier\SubCategory\SubCategory

    lighthouse.core.document.repository.user:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\User\User
        arguments:
            - LighthouseCoreBundle:User\User

    lighthouse.core.document.repository.client:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\Auth\Client
        arguments:
            - LighthouseCoreBundle:Auth\Client

    lighthouse.core.document.repository.store:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\Store\Store
        arguments:
            - LighthouseCoreBundle:Store\Store

    lighthouse.core.document.repository.department:
            parent: doctrine_mongodb.odm.repository
            class: Lighthouse\CoreBundle\Document\Department\Department
            arguments:
                - LighthouseCoreBundle:Department\Department

    lighthouse.core.document.repository.product_version:
            parent: doctrine_mongodb.odm.repository
            class: Lighthouse\CoreBundle\Versionable\VersionRepository
            arguments:
                - LighthouseCoreBundle:Product\Version\ProductVersion
            calls:
                - [setVersionFactory, ["@lighthouse.core.versionable.factory"]]