parameters:
    money.digits: 2

services:
    jms_serializer.serialized_name_annotation_strategy:
        class: %jms_serializer.serialized_name_annotation_strategy.class%
        public: false
        arguments: ["@lighthouse.core.naming.as_is"]

    jms_serializer.metadata_driver:
        alias: lighthouse.core.serializer.metadata.driver.document

    doctrine_mongodb.odm.repository:
        abstract: true
        class: Doctrine\ODM\MongoDB\DocumentRepository
        factory_service: doctrine_mongodb.odm.document_manager
        factory_method: getRepository

    lighthouse.core.document.repository.product:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\Product\ProductRepository
        arguments:
            - LighthouseCoreBundle:Product\Product

    lighthouse.core.document.repository.invoice:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\Invoice\InvoiceRepository
        arguments:
            - LighthouseCoreBundle:Invoice\Invoice

    lighthouse.core.document.repository.invoice_product:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\InvoiceProduct\InvoiceProductRepository
        arguments:
            - LighthouseCoreBundle:InvoiceProduct\InvoiceProduct

    lighthouse.core.document.repository.trial_balance:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\TrialBalance\TrialBalanceRepository
        arguments:
            - LighthouseCoreBundle:TrialBalance\TrialBalance

    lighthouse.core.document.repository.purchase:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\Purchase\PurchaseRepository
        arguments:
            - LighthouseCoreBundle:Purchase\Purchase

    lighthouse.core.document.repository.writeoff:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\WriteOff\WriteOffRepository
        arguments:
            - LighthouseCoreBundle:WriteOff\WriteOff

    lighthouse.core.document.repository.writeoff.product:
        parent: doctrine_mongodb.odm.repository
        class: Lighthouse\CoreBundle\Document\WriteOff\Product\WriteOffProductRepository
        arguments:
            - LighthouseCoreBundle:WriteOff\Product\WriteOffProduct
